### ISSUE TITLE
getting "was collected before with the same name and label values"

### ISSUE THREAD

**Issue by dgttm** [openstack-exporter/openstack-exporter#80] opened 2020-01-27 10:33 UTC
Hello,

I just upgraded from an older version in an multi customer, kolla-ansible deloyed openstack rocky, but I get the following errors (only on prod, on stage and dev its running fine).

```
INFO[0030] Collecting metrics for exporter: openstack_nova, metric: security_groups  source="exporter.go:88"
INFO[0031] Collecting metrics for exporter: openstack_cinder, metric: snapshots  source="exporter.go:88"
INFO[0031] Collecting metrics for exporter: openstack_nova, metric: vcpus_used  source="exporter.go:88"
INFO[0031] Collecting metrics for exporter: openstack_nova, metric: memory_available_bytes  source="exporter.go:88"
INFO[0031] Collecting metrics for exporter: openstack_nova, metric: local_storage_used_bytes  source="exporter.go:88"
An error has occurred while serving metrics:

16 error(s) occurred:
* collected metric "openstack_nova_limits_vcpus_max" { label:<name:"tenant" value:"projekt1" > gauge:<value:80 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_used" { label:<name:"tenant" value:"projekt1" > gauge:<value:6 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_max" { label:<name:"tenant" value:"projekt1" > gauge:<value:262144 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_used" { label:<name:"tenant" value:"projekt1" > gauge:<value:12288 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_max" { label:<name:"tenant" value:"projekt1" > gauge:<value:80 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_used" { label:<name:"tenant" value:"projekt1" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_max" { label:<name:"tenant" value:"projekt1" > gauge:<value:262144 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_used" { label:<name:"tenant" value:"projekt1" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_max" { label:<name:"tenant" value:"musterproject" > gauge:<value:80 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_used" { label:<name:"tenant" value:"musterproject" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_max" { label:<name:"tenant" value:"musterproject" > gauge:<value:262144 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_used" { label:<name:"tenant" value:"musterproject" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_max" { label:<name:"tenant" value:"main" > gauge:<value:80 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_vcpus_used" { label:<name:"tenant" value:"main" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_max" { label:<name:"tenant" value:"main" > gauge:<value:262144 > } was collected before with the same name and label values
* collected metric "openstack_nova_limits_memory_used" { label:<name:"tenant" value:"main" > gauge:<value:0 > } was collected before with the same name and label values
INFO[0033] Collecting metrics for exporter: openstack_neutron, metric: agent_state  source="exporter.go:88"
INFO[0038] Collecting metrics for exporter: openstack_nova, metric: limits_vcpus_used  source="exporter.go:88"
INFO[0038] Collecting metrics for exporter: openstack_nova, metric: availability_zones  source="exporter.go:88"
INFO[0038] Collecting metrics for exporter: openstack_nova, metric: security_groups  source="exporter.go:88"
INFO[0039] Collecting metrics for exporter: openstack_nova, metric: vcpus_used  source="exporter.go:88"

```

any help appreciated! thanks a lot !

**Comment by vooon** [comment] 2020-02-03 10:04
Got similar issue, but the problem is that other metrics is not published as well (`curl http://localhost:9180/metrics` responds with errors list).

From logs i see that exporter fails on projects closed for exporter user for security reasons.

So to fix, need a way to ignore closed projects.

**Comment by niedbalski** [comment] 2020-03-27 13:54
@vooon this should be fixed in master and will be released on 1.0.0, fixed by #93

**Closed by niedbalski** 2020-03-27 13:54 UTC

**Comment by vooon** [comment] 2020-03-29 08:08
@niedbalski, I will check on coming week and write you back. Thanks!

**Comment by vooon** [comment] 2020-04-02 13:16
@niedbalski works like a charm! Thanks!
