### ISSUE TITLE
cinder.go does not respect the TLS config settings

### ISSUE THREAD

**Issue by marklcg** [openstack-exporter/openstack-exporter#15] opened 2019-07-19 17:30 UTC
It looks like the cinder.go source is missing the code necessary to respect the tlsConfig settings as seen in exporter.go.

```go
tlsConfig, err := config.GetTLSConfig()
if err != nil {
    return nil, err
}

if tlsConfig != nil {
    log.Infoln("using TLS configured SSL connection")
    newClient = client.NewClientTLSConfig(&credentials, authMode, nil, tlsConfig)
} else {
    log.Infoln("using non TLS configured SSL connection")
    newClient = client.NewClient(&credentials, authMode, nil)
}
```

**Comment by niedbalski** [comment] 2019-07-19 17:36
@marklcg 

Hello mark,

Thanks for your report. What's the problem/bug/error you are seeing due to this?

**Comment by marklcg** [comment] 2019-07-19 17:46
Certificate trust issues in our case.  We can work around it by adding the certs to /etc/ssl in our container.  So we do have a work around.

**Comment by niedbalski** [comment] 2019-07-19 18:05
The TLSConfig is defined before the cinder exporter gets instantiated, Do you have any traceback/debug logs to see the specific error you are seeing?

**Comment by marklcg** [comment] 2019-07-19 20:07
Sure, we were seeing this error even with our cloud auth.verify set to false.  It ignores the cert for all the other metrics, just not cinder:

```txt
[1:12 PM] Tom Dombrosky
    
time="2019-07-19T17:09:07Z" level=error msg="Get https://10.40.9.50:13776/v3/51285243fc0241e9ab74efb20a0736b2/volumes?all_tenants=1: Get https://10.40.9.50:13776/v3/51285243fc0241e9ab74efb20a0736b2/volumes?all_tenants=1: x509: certificate signed by unknown authority" source="cinder.go:92"
```

**Comment by niedbalski** [comment] 2019-07-19 20:47
@marklcg 

Thank you for the detailed report. Could you please test the latest image from [0] master and report on this bug?, this commit [1] should pass the tls configuration to the cinder client as it's done with the other service exporters.

[0] quay.io/niedbalski/openstack-exporter-linux-amd64:master
[1] https://github.com/openstack-exporter/openstack-exporter/commit/6c96a2ff7c07ed4f8be3690367cccb76c6c09820

**Comment by niedbalski** [comment] 2019-07-22 14:13
@marklcg 

I've tested it with verify false and a set of self-signed certificates, all seems to work. I am waiting on your confirmation to release 0.2.0 

Thank you

**Comment by marklcg** [comment] 2019-07-22 16:02
Sorry for slow response, I'll see if we can grab the latest to confirm, but I suspect you are correct--we were using an old version.  I'm OK with closing this for now and if we see it with the latest when we get to it, re-opening.  Sound OK?

**Comment by niedbalski** [comment] 2019-07-22 16:09
@marklcg 

I think is a valid bug, can you check the latest master image to see if the problem is still reproducible?

Thanks

**Comment by marklcg** [comment] 2019-07-23 14:41
We were able to validate that the latest master does work.

**Comment by niedbalski** [comment] 2019-07-23 14:42
Thanks, marking this as fixed.

**Closed by niedbalski** 2019-07-23 14:42 UTC
Labels: bug
